### ISSUE TITLE
Does not output debug information to docker

### ISSUE THREAD

**Issue by pomazanbohdan** [onyx-dot-app/onyx#1239]
```
services:
  api_server:
    image: danswer/danswer-backend:latest
....
    environment:
      - LOG_LEVEL=debug
```
Log:

```
api_server-1  | FAILED: Can't locate revision identified by '173cae5bba26'
api_server-1  | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
api_server-1  | INFO  [alembic.runtime.migration] Will assume transactional DDL.
api_server-1  | ERROR [alembic.util.messaging] Can't locate revision identified by '173cae5bba26'
api_server-1  | FAILED: Can't locate revision identified by '173cae5bba26'
api_server-1  | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
api_server-1  | INFO  [alembic.runtime.migration] Will assume transactional DDL.
api_server-1  | ERROR [alembic.util.messaging] Can't locate revision identified by '173cae5bba26'
api_server-1  | FAILED: Can't locate revision identified by '173cae5bba26'

```
